### ISSUE TITLE
Failed To Build in RPI4 

### ISSUE THREAD

**Issue by AbdullahJerjawi** [GrahamBriggs/bcibeginner#1]
Hello guys, thank you for this great tool,
I am try to build BrainHat Server on Raspberry Pi 4 (2GB) and when running `make CONFIG=Release` then I got these errors in picture:
![WhatsApp Image 2021-04-24 at 10 31 40 PM](https://user-images.githubusercontent.com/83138444/115970723-eef40880-a54c-11eb-9ad5-7d06ae72cfb9.jpeg)

It says **/usr/bin/ld: skipping incompatible** for all libraries, note that I have executed `deployBrainHatLib` in `lib` folder without any issues, I believe that the libraries need to re-compiled for the latest version of Raspberry PI, any thoughts?

**Comment by AbdullahJerjawi** [comment]
@GrahamBriggs

**Comment by GrahamBriggs** [comment]
It looks like you are trying to build on 64 bit RPi OS.  The system only works on Raspberry Pi OS (32 bit).

You would have to recompile the libraries for 64 bit:
- LSL
- brainflow
- EDFFile
- wiringPi (although this one is optional and can be removed)

**Comment by GrahamBriggs** [comment]
@AbdullahJerjawi  If 64 bit is not a hard requirement for you, please consider starting with our pre made Raspberry Pi OS image. More information can be found here:  [https://openbci.com/community/brainhat-mobile-openbci-off-the-grid-mobile-recording/](https://openbci.com/community/brainhat-mobile-openbci-off-the-grid-mobile-recording/)

**Comment by AbdullahJerjawi** [comment]
Hello guys, thank you for this great tool,
I am try to run BrainHat Server on Raspberry Pi 4 (2GB) and when running make errors in picture these errors appear when I Plug in your OpenBCI USB dongle to the Raspberry Pi, and run the program with command line arguments to specify your board type     ./brainHat --board-id 1 --serial-port /dev/ttyACM0  :
![Error](https://user-images.githubusercontent.com/83138444/116005039-fe875600-a60d-11eb-8c42-53179855ecf9.PNG)
