### ISSUE TITLE
The Arduino connection with Ganglion board 

### ISSUE THREAD

**Issue by AbdullahJerjawi** [GrahamBriggs/bcibeginner#3]
Hello guys, thank you for this great tool,
I have  Ganglion board and I am try to run  on Raspberry Pi 4 (2GB) and when I try the board can not connection with the raspberry pi4 so I want to connection with the Arduino and I don't have a information a bout how I connect the Arduino with ganglion I need to know there is a libraries on the Arduino and how I can connection the hardware

**Comment by GrahamBriggs** [comment]
I have no idea if this project will work on Arduino. It has only been tested on Raspberry Pi. The brainHat system uses lab streaming layer for data broadcast, so it requires a TCPIP network stack. It might work on Arduino if you have WiFi shield, but I can not say for sure if it will compile. Good luck.

Depending on what you are eventually trying to build, and how close (or far away) that is to the brainHat system, you may be better off by using the [brainflow libraries ](https://github.com/brainflow-dev/brainflow) directly in your project
